WebECApp/WebECApp/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebECApp.Models
{
    public class Product
    {
        //creating a class with different data properties
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
        public string ProductImage { get; set; }
        public string Image_2 { get; set; }
        public string Image_3 { get; set; }
        public string Image_4 { get; set; }
        public string Image_5 { get; set; }
        public string Image_6 { get; set; }
        public ICollection<Comment> Comments { get; set; }
    }
}

WebECApp/WebECApp/Models/Return.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebECApp.Models
{
    public class Return
    {
        public int ReturnID { get; set; }
        public string ProductName { get; set; }
        public string DatePurchased { get; set; }
        public DateTime TimeStamp { get; set; }
        public string UserId { get; set; }
        public string Reason { get; set; }
    }
}

WebECApp/WebECApp/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebECApp.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebECApp/WebECApp/Pages/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebECApp.Models;

namespace WebECApp.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly AppDataContext _db;
        // cart property of type list inheriting from cart class
        public List<Cart> Cart { get; set; }
        public decimal Total { get; set; }

        public CheckoutModel(AppDataContext db)
        {
            _db = db;
        }
        //obtaining list of items stored in session displaying in cart and calculating total
        public void OnGet()             
        {
            Carts = new Cart();
            Cart = SessionHelp.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
            Total = 10 + Cart.Sum(Cart => Cart.Product.Price * Cart.Quantity);
        }
        // storing items from the product page in session throug id parameter
        public IActionResult OnGetBuy(string id)               //(inspired from https://learningprogramming.net/net/asp-net-core-mvc/ )
        {
            var Product = _db.Products.Find(id);
            var cart = SessionHelp.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
            // defining condition product added to empty cart
            if (cart == null)
            {
                cart = new List<Cart>();
                cart.Add(new Cart()
                {
                    Product = Product,
                    Quantity = 1
                });
                // storing in session
                SessionHelp.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            // defining condition for an item already being present in cart
            else
            {
                var index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new Cart()
                    {
                        Product = Product,
                        Quantity = 1
                    });
                }
                // definig condition for an item added twice(increments quantity property)
                else
                {
                    var newQuantity = cart[index].Quantity + 1;
                    cart[index].Quantity = newQuantity;
                }
                SessionHelp.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            // showing checkout everytime an item is added
            return RedirectToPage("Checkout");
        }
        // removing an item from cart through id parameter
        public IActionResult OnGetDelete(string id)
        {
            var cart = SessionHelp.GetObjectFromJson<List<Cart>>(HttpContext.Session, "cart");
            var index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelp.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Checkout");
        }
        // defining the conditions for adding same item to cart twice
        private int Exists(List<Cart> cart, string id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        // storing our purchases to our sales database
        [BindProperty]
        public Cart Carts { get; set; }
        public IActionResult OnPost()
        {
            _db.Sales.Add(Carts);
            _db.SaveChanges();
            return RedirectToPage("Index");
        }
    }
}

WebECApp/WebECApp/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebECApp.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebECApp/WebECApp/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebECApp.Models;

namespace WebECApp.Pages
{
    public class DetailsModel : PageModel
    {
        public readonly AppDataContext _db;
        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }
        public Product Products { get; set; }
        // defining comments property and binding for passing data
        [BindProperty(SupportsGet = true)]
        public Comment Comments { get; set; }
        public DetailsModel(AppDataContext db)
        {
            _db = db;
        }
        // getting at routed product through id
        public void OnGet()
        {
            Comments = new Comment();
            Products = _db.Products.Find(Id);
        }
        // uploading comments to comments table
        public IActionResult OnPost()
        {
            _db.Comments.Add(Comments);
            _db.SaveChanges();
            return RedirectToPage("Products");
        }
    }
}

WebECApp/WebECApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebECApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebECApp/WebECApp/Pages/Exclusives.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebECApp.Models;

namespace WebECApp.Pages
{
    // creating an exclusive section for registered user to view specified range of products
    [Authorize]
    public class ExclusivesModel : PageModel
    {
        public readonly AppDataContext _db;

        public ExclusivesModel(AppDataContext db)
        {
            _db = db;
        }
        [BindProperty(SupportsGet = true)]
        public List<Product> Products { get; set; }
        public void OnGet()
        {
            Products = _db.Products.OrderByDescending(x => x.Id).Take(3).ToList();
        }
    }
}

WebECApp/WebECApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebECApp.Models;

namespace WebECApp.Pages
{
    public class IndexModel : PageModel
    {
        public readonly AppDataContext _db;
        public List<Product> Products { get; set; } = new List<Product>();
        public IList<Comment> Comments { get; set; }
        public IndexModel(AppDataContext db)
        {
            _db = db;
        }
        // getting as a specified range of products and comments for our index page
        public void OnGet()
        {
            Comments = _db.Comments.OrderByDescending(x => x.CommentID).Take(3).ToList();
            Products = _db.Products.OrderByDescending(x => x.Id).Take(12).ToList();
        }
    }
}

WebECApp/WebECApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebECApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebECApp/WebECApp/Pages/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebECApp.Models;

namespace WebECApp.Pages
{
    public class ProductsModel : PageModel
    {
        public readonly AppDataContext _db;

        public ProductsModel(AppDataContext db)
        {
            _db = db;
        }
        // Enables the information found in our db on the products table to be displayed as list
        [BindProperty(SupportsGet = true)]
        public IList<Product> Products { get; set; } 
        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }
        public SelectList Brand { get; set; }    // specifying we want to get at different brands as a list
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string ProdBrand { get; set; }
        public SelectList Category { get; set; }
        [BindProperty(SupportsGet = true)]
        [ViewData]
        public string ProdCategory { get; set; }
        [BindProperty(SupportsGet = true)]
        public string StringSearch { get; set; }
        // renders a list of the properties in our table when a get request is made by the page
        public async Task OnGetAsync()
        {
            IQueryable<string> brandQuery = from m in _db.Products           //getting the list of brands
                                            orderby m.Brand
                                            select m.Brand;
            IQueryable<string> catQuery = from m in _db.Products           //getting the list of Categories
                                          orderby m.Category
                                          select m.Category;
            var products = from m in _db.Products
                           select m;
            if (!string.IsNullOrEmpty(StringSearch))
            {
                products = products.Where(s => s.Name.Contains(StringSearch));
            }
            if (!string.IsNullOrEmpty(ProdBrand))
            {
                products = products.Where(x => x.Brand == ProdBrand);
            }
            if (!string.IsNullOrEmpty(ProdCategory))
            {
                products = products.Where(x => x.Category == ProdCategory);
            }
            Category = new SelectList(await catQuery.Distinct().ToListAsync());
            Brand = new SelectList(await brandQuery.Distinct().ToListAsync());
            Products = await products.ToListAsync();

        }
    }
}

WebECApp/WebECApp/Pages/Return.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebECApp.Models;

namespace WebECApp.Pages
{
    [Authorize]
    public class ReturnModel : PageModel
    {
        public readonly AppDataContext _db; // allowing our datacontext to be readable by everyone
        [BindProperty]
        public Return Returns { get; set; } 
        public ReturnModel(AppDataContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            Returns = new Return();
        }
        // sends information from our form to our data base using the add method and saves the changes using the SaveChanges method and returns the admins Page 
        public IActionResult OnPost()
        {
            _db.Returns.Add(Returns);
            _db.SaveChanges();
            return RedirectToPage("About");
        }
    }
}

WebECApp/WebECApp/Pages/About.cshtml
@page
@model WebECApp.Pages.AboutModel
@{
}
<div class="smallcontainer">
    <div class="row">
        <div class="myplayer">
            <video id="myvideo" autoplay>
                <source src="/images/company-update-copy.mp4" type="video/mp4">
            </video>
            <br>
            <div class="controls">
                <button id="playbttn">Pause</button>
                <button id="stopbttn">Stop</button>
                <input id="slider" type="range" min="0" max="100" value="0">
                <span id="currenttime"></span> / <span id="durationtime"></span>
                <button id="volctrl">Mute</button>
                <input id="volslide" type="range" min="0" max="100" value="100">
            </div>
        </div>
    </div>
    <br />
</div>
<br />
<br />
<div class="smallcontainer">
    <div class="row">
        <h3 class="title">Return Policy</h3>
        <p>
            Mills legacy has a maintained a direct customer centric policy over the years. Products which
            our customers find dissatisying or which arrive with unforseen damages may be shipped back within a 15day time
            frame. A <a href="Return"><small>return form</small></a> is made available for our customers to help manage this. It should be notted that
            Mills legacy doesnt do full cash refund on payments made but will allow customers pick an article of same
            or atleast three quarters the value of the originally purchased item and the difference will be paid to them
            through the initial method of payment.
        </p>
    </div>
</div>
<div class="row">
    <a href="Return" class="bot" >Return form</a>
</div>
<div class="row">
    <hr />
    <a asp-page="Admin/Admin"><small>Privacy</small></a>
</div>


<script type="text/javascript">
    // set object refernces
    var vid = document.getElementById("myvideo");
    var currenttime = document.getElementById("currenttime");
    var durationtime = document.getElementById("durationtime");
    var plbttn = document.getElementById("playbttn");
    var vol = document.getElementById("volctrl");
    var stopbtn = document.getElementById("stopbttn");
    var slide = document.getElementById("slider");
    var volslide = document.getElementById("volslide");

    //play/pause vid function
    function playvid() {
        if (vid.paused) {
            vid.play();
            plbttn.innerHTML = "Pause";
        } else {
            vid.pause();
            plbttn.innerHTML = "Play";
        }
    }
    // stop function
    function stopvid() {
        vid.pause();
        vid.currentTime = 0;
        plbttn.innerHTML = "Play";
    }
    //volume function
    function volvid() {
        if (vid.muted) {
            vid.muted = false;
            volslide.value = 100;
            vol.innerHTML = "Mute";
        } else {
            vid.muted = true;
            volslide.value = 0;
            vol.innerHTML = "Unmute";
        }
    }
    // volume slider
    function volslidvid() {
        vid.volume = volslide.value / 100;

    }
    // video slider(clicking)
    function slidevid() {
        vid.currentTime = vid.duration * (slide.value / 100);
    }
    // video slider(pulling)
    function movevid() {
        slide.value = vid.currentTime * (100 / vid.duration);
        var mins = Math.floor(vid.currentTime / 60);
        var secs = Math.floor(vid.currentTime - mins * 60);
        var duramins = Math.floor(vid.duration / 60);
        var durasecs = Math.floor(vid.duration - mins * 60);
        if (secs < 10) {
            secs = "0" + secs;
        }
        if (durasecs < 10) {
            durasecs = "0" + durasecs;
        }
        if (mins < 10) {
            mins = "0" + mins;
        }
        if (duramins < 10) {
            duramins = "0" + duramins;
        }
        currenttime.innerHTML = mins + ":" + secs;
        durationtime.innerHTML = duramins + ":" + durasecs;
    }

    // adding event listeners
    plbttn.addEventListener("click", playvid);
    vol.addEventListener("click", volvid);
    stopbtn.addEventListener("click", stopvid);
    slide.addEventListener("change", slidevid);
    vid.addEventListener("timeupdate", movevid);
    volslide.addEventListener("change", volslidvid);
</script>

WebECApp/WebECApp/Pages/Checkout.cshtml
@page
@model WebECApp.Pages.CheckoutModel
@{
}
<body>
    <div class="smallcontainer cartpage">
        <table>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Select Size</th>
                <th>Subtotal</th>
            </tr>

            @foreach (var cart in Model.Cart)
            {
                <tr>
                    <td>
                        <div class="cartinfo">
                            <img src="/images/@cart.Product.ProductImage" width="120" />
                            <div>
                                <p>@cart.Product.Name</p>
                                <small>£@cart.Product.Price</small>
                                <br>
                                <a asp-page="Checkout" asp-page-handler="delete" asp-route-id="@cart.Product.Id">remove</a>
                            </div>
                        </div>
                    </td>
                    <td>@cart.Quantity</td>
                    <td>
                        <select>
                            <option>select size</option>
                            <option>small</option>
                            <option>medium</option>
                            <option>large</option>
                            <option>extra large</option>
                        </select>
                    </td>
                    <td>£@(cart.Product.Price * cart.Quantity)</td>
                </tr>
            }
        </table>
        <div class="total-price">
            <table>
                <tr>
                    <td>Delivery</td>
                    <td>£10.00</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>£@Model.Total</td>
                </tr>
            </table>
            <br />
        </div>
        <br />
        <a asp-page="Products" class="btn">continue shopping</a>
    </div>
    <br />
    <form method="post">
        @foreach (var cart in Model.Cart)
        {
            <input type="hidden" asp-for="@Model.Carts.Name" value="@cart.Product.Name" />
            <input type="hidden" asp-for="@Model.Carts.DateTime" value="@DateTime.Now" />
            <input type="hidden" asp-for="@Model.Carts.UserID" value="@User.Identity.Name" />
            <input type="hidden" asp-for="@Model.Carts.ProductID" value="@cart.Product.Id" />
            <input type="hidden" asp-for="@Model.Carts.Quantity" value="@cart.Quantity" />
            <input type="hidden" asp-for="@Model.Carts.Total" value="@(cart.Quantity * cart.Product.Price)" />
        }

        <input type="submit" class="btn" value="Confirm Purchase" />
    </form>

</body>

WebECApp/WebECApp/Pages/Contact.cshtml
@page
@model WebECApp.Pages.ContactModel
@{
}
<div class="small-container">
    <h2 class="title">Contact Us</h2>
    <div class="row">
        <div class="btn">
            <a href="">Telephone: +44 7719 880348</a>
        </div>
    </div>
    <div class="row">
        <div class="btn">
            <a href="">E-Mail: samkiakehbuma@gmail.com</a>
        </div>
    </div>
    <div>
        <h2 class="title"> Social Media</h2>
    </div>
    <div class="row">
        <div class="col-1">
            <a href="https://www.facebook.com/mills.legacy.54"><img src="~/images/facebook-logoJ.jpg" width="200" height="200" alt="Facebook"></a>
            <a href="https://twitter.com/MillsLegacy"><img src="~/images/twitter-logo.png" width="200" height="200" alt="Twitter"></a>
            <a href="https://studio.youtube.com/channel/UCa0Z8dbQLmu7iWIQjg9y0CA/videos/upload?filter=%5B%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D"><img src="~/images/YouTube-logoJ.jpg" width="200" height="200" alt="YouTube"></a>
            <a href="https://www.instagram.com/mills_legacy/"><img src="~/images/instagram-logo.png" width="200" height="200" alt="Instagram"></a>
        </div>
    </div>
    <div class="col-2">
        <p>We are here to provide you with all the assistace you need</p>
    </div>
</div>

WebECApp/WebECApp/Pages/Details.cshtml
@page "{Id}"
@model WebECApp.Pages.DetailsModel
@{
}

<body>
    <div class="container">
        <a href="##" onClick="history.go(-1); return false;">Go back</a>
        <hr />
        <div class="smallcontainer">
            <div class="single-product">
                <div class="row">
                    <div class="col-2">
                        <img src="/images/@Model.Products.ProductImage" width="500" id="productimg">
                    </div>
                    <div class="col-2">
                        <small>@Model.Products.Category/@Model.Products.Brand</small>
                        <h1>@Model.Products.Name</h1>
                        <h4>£@Model.Products.Price</h4>
                        <h3>Product Details <i class="fa fa-indent"></i></h3>
                        <br>
                        <p>@Model.Products.Description</p>
                    </div>
                    <div class="smallimgrow">
                        <div class="smallimgcol">
                            <img src="/images/@Model.Products.Image_2" width="100" class="smallimg">
                        </div>
                        <div class="smallimgcol">
                            <img src="/images/@Model.Products.Image_3" width="100" class="smallimg">
                        </div>
                        <div class="smallimgcol">
                            <img src="/images/@Model.Products.Image_4" width="100" class="smallimg">
                        </div>
                        <div class="smallimgcol">
                            <img src="/images/@Model.Products.Image_5" width="100" class="smallimg">
                        </div>
                        <div class="smallimgcol">
                            <img src="/images/@Model.Products.Image_6" width="100" class="smallimg">
                        </div>
                    </div>
                    <div class="row">
                        <a asp-page="Checkout" asp-page-handler="buy" class="btn" asp-route-id="@Model.Products.Id" title="@Model.Products.Name">Order Now</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="smallcontainer">
            <div class="row row-2">
            </div>
        </div>
        <div class="smallcontainer">
            <div class="row">
                <form method="post" id="commentform">
                    <input type="hidden" asp-for="@Model.Comments.CommentID" value="" />
                    <input type="hidden" asp-for="@Model.Comments.TimeStamp" value="@DateTime.Now" />
                    <input type="hidden" asp-for="@Model.Comments.UserId" value="@User.Identity.Name" />
                    <input type="hidden" asp-for="@Model.Comments.ProductId" value="@Model.Products.Id" />
                    <div class="form-group">
                        <div class="row row-2">
                            <p>please give a star rating on 5</p>
                            <span class="text-warning float-right">
                                <i class="Ratingstar fa fa-star"></i>
                                <input asp-for="@Model.Comments.Ratings" min="1" max="5" />
                            </span>
                        </div>
                        <label>Please Enter Your Comment</label>
                        <textarea class="form-control" rows="3" asp-for="@Model.Comments.Text" placeholder="write your comment here."></textarea>
                    </div>
                    <button class="btn" type="submit">Leave Comment</button>
                </form>
            </div>
        </div>
    </div>
</body>

WebECApp/WebECApp/Pages/Exclusives.cshtml
@page
@model WebECApp.Pages.ExclusivesModel
@{
    ViewData["Title"] = "Exclusives page";
}
<div class="smallcontainer">
    <small>@ViewData["Title"]</small>
    @foreach (var product in Model.Products)
    {
        <div class="single-product">
            <div class="row">
                <div class="col-2">
                    <img src="/images/@product.ProductImage" width="500" id="productimg">
                </div>
                <div class="col-2">
                    <small>@product.Category/@product.Brand</small>
                    <h1>@product.Name</h1>
                    <h4>£@product.Price</h4>
                    <h3>Product Details <i class="fa fa-indent"></i></h3>
                    <br>
                    <p>@product.Description</p>
                </div>
                <div class="smallimgrow">
                    <div class="smallimgcol">
                        <img src="/images/@product.Image_2" width="100" class="smallimg">
                    </div>
                    <div class="smallimgcol">
                        <img src="/images/@product.Image_3" width="100" class="smallimg">
                    </div>
                    <div class="smallimgcol">
                        <img src="/images/@product.Image_4" width="100" class="smallimg">
                    </div>
                    <div class="smallimgcol">
                        <img src="/images/@product.Image_5" width="100" class="smallimg">
                    </div>
                    <div class="smallimgcol">
                        <img src="/images/@product.Image_6" width="100" class="smallimg">
                    </div>
                </div>
            </div>
        </div>
    }


</div>

WebECApp/WebECApp/Pages/Products.cshtml
@page
@model WebECApp.Pages.ProductsModel
@{
}
@{
    ViewData["Title"] = "Products";
}

<body>
    <h3>@ViewData["Title"]/@ViewData["ProdBrand"]/@ViewData["ProdCategory"]</h3>

    <div class="smallcontainer">
        <div class="row row-2">
            <h2>All Products</h2>
            <form method="get">
                <input type="text" asp-for="StringSearch" />
                <input type="submit" value="search" />
            </form>
            <form>
                <select asp-for="ProdBrand" asp-items="Model.Brand">
                    <optgroup label="Sort By Brand">
                        <option value="">Sort By Brand</option>
                    </optgroup>
                </select>
                <select asp-for="ProdCategory" asp-items="Model.Category">
                    <optgroup label="Sort By Category">
                        <option value="">Sort By Category</option>
                    </optgroup>
                </select>
                <input type="submit" value="Go" />
            </form>


        </div>
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-4">
                    <a asp-page="Details" asp-route-id="@product.Id" title="@product.Name"><img src="/images/@product.ProductImage" alt="@product.Name"></a>
                    <h4>@product.Name</h4>
                    <p class="Price">£@product.Price</p>
                    <a asp-page="Checkout" class="btn" asp-page-handler="buy" asp-route-id="@product.Id" title="@product.Name">Order Now</a>
                </div>
            }
        </div>
    </div>
</body>

WebECApp/WebECApp/Pages/Return.cshtml
@page
@model WebECApp.Pages.ReturnModel
@{
    Layout = "_FormLayout";
}
<div class="row">
    <div class="col-2">
        <form method="post">
            <div>
                <label asp-for="@Model.Returns.ReturnID"></label>
                <div>
                    <input asp-for="@Model.Returns.ReturnID" readonly="readonly" />
                    <span asp-validation-for="@Model.Returns.ReturnID" class="text-danger"></span>
                </div>
            </div>
            <div>
                <label asp-for="@Model.Returns.Reason"></label>
                <div>
                    <input asp-for="@Model.Returns.Reason" />
                    <span asp-validation-for="@Model.Returns.Reason" class="text-danger"></span>
                </div>
            </div>
            <div>
                <label asp-for="@Model.Returns.TimeStamp"></label>
                <div>
                    <input asp-for="@Model.Returns.TimeStamp" placeholder="enter date purchased here" />
                    <span asp-validation-for="@Model.Returns.TimeStamp" class="text-danger"></span>
                </div>
            </div>
            <div>
                <label asp-for="@Model.Returns.ProductName"></label>
                <div>
                    <input asp-for="@Model.Returns.ProductName" />
                    <span asp-validation-for="@Model.Returns.ProductName" class="text-danger"></span>
                </div>
            </div>
            <div>
                <label asp-for="@Model.Returns.UserId"></label>
                <div>
                    <input asp-for="@Model.Returns.UserId" value="@User.Identity.Name" />
                    <span asp-validation-for="@Model.Returns.UserId" class="text-danger"></span>
                </div>
            </div>
            <div>
                <label asp-for="@Model.Returns.DatePurchased"></label>
                <div>
                    <input asp-for="@Model.Returns.DatePurchased" value="@DateTime.Now" type="hidden" />
                    <span asp-validation-for="@Model.Returns.DatePurchased" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div>
                <input type="submit" value="Add Product" />
            </div>
        </form>
    </div>
    <div class="col-2">
        <div class="logo">
            <img src="~/images/default.png" width="300">
        </div>
    </div>
</div>